// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:greenhouse/config.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Config.webApiKey,
    appId: Config.appId,
    messagingSenderId: Config.messagingSenderId,
    projectId: 're-greenhouse',
    authDomain: 're-greenhouse.firebaseapp.com',
    storageBucket: 're-greenhouse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Config.androidApiKey,
    appId: Config.appId,
    messagingSenderId: Config.messagingSenderId,
    projectId: 're-greenhouse',
    storageBucket: 're-greenhouse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Config.iosApiKey,
    appId: Config.appId,
    messagingSenderId: Config.messagingSenderId,
    projectId: 're-greenhouse',
    storageBucket: 're-greenhouse.firebasestorage.app',
    iosBundleId: 'com.example.greenhouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: Config.macosApiKey,
    appId: Config.appId,
    messagingSenderId: Config.messagingSenderId,
    projectId: 're-greenhouse',
    storageBucket: 're-greenhouse.firebasestorage.app',
    iosBundleId: 'com.example.greenhouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: Config.windowsApiKey,
    appId: Config.appId,
    messagingSenderId: Config.messagingSenderId,
    projectId: 're-greenhouse',
    authDomain: 're-greenhouse.firebaseapp.com',
    storageBucket: 're-greenhouse.firebasestorage.app',
  );
}
